### ISSUE TITLE
Kill Command

### ISSUE THREAD

**Issue by Miller-Whighte** [Aardenfell/TheHolyAutomation#5]
**Problem to Ease.**
Kill contributions are difficult to distribute rewards for.

**Describe the solution you'd like**
A /kill command that functions much like the /participation command. Affixes/Tags would include:
Amount of Kills (with a selection of 10/20/30...up to 100+)
Participants (user adds participants that earned within that bracket of kills)

**Describe alternatives you've considered**
Haven't given thought to other methods, this solution is fairly reasonable and was inspired by the participation command already in use.

**Additional context**
Points would be rewarded at a .1 multiplier of kills for most players, a .2 multiplier for SnS main weapon users, and a .3 multiplier for Wand main weapon users.

**Comment by Aardenfell** [comment]
@Miller-Whighte 
> **Problem to Ease.** Kill contributions are difficult to distribute rewards for.
> 
> **Describe the solution you'd like** A /kill command that functions much like the /participation command. Affixes/Tags would include: Amount of Kills (with a selection of 10/20/30...up to 100+) Participants (user adds participants that earned within that bracket of kills)
> 
> **Describe alternatives you've considered** Haven't given thought to other methods, this solution is fairly reasonable and was inspired by the participation command already in use.
> 
> **Additional context** Points would be rewarded at a .1 multiplier of kills for most players, a .2 multiplier for SnS main weapon users, and a .3 multiplier for Wand main weapon users.


Here's what I had in mind, lemme know if I got what you wanted right.

### `/kills` Command Documentation

#### **Command Syntax**
```
/kills participants:<@mentions or IDs> bracket:<kill bracket> [class:<class modifier>] [reason:<reason>]
```

---

#### **Parameters**
1. **`participants`** (Required)
   - **Description**: A space-separated list of mentions (`@user`) or user IDs for participants receiving rewards.
   - **Example**: `@user1 @user2 @user3` or `123456789012345678 987654321098765432`

2. **`bracket`** (Required)
   - **Description**: The kill bracket indicating the number of kills participants contributed to.
   - **Available Choices**:
     - `10`
     - `20`
     - `30`
     - `40`
     - `50`
     - `...`
     - `100+`
   - **Example**: `10`, `50`, `100+`

3. **`class`** (Optional)
   - **Description**: A modifier for participants based on their primary weapon class, affecting the reward multiplier.
   - **Available Choices**:
     - `tank` (0.2 multiplier)
     - `healer` (0.3 multiplier)
     - Default (0.1 multiplier if not specified)
   - **Example**: `tank`, `healer`

4. **`reason`** (Optional)
   - **Description**: The reason for the reward distribution.
   - **Default Value**: `"Rewards for kill contributions in bracket <bracket>"`
   - **Example**: `"Kill contribution during the raid."`

---

#### **Reward Calculation**
- **Formula**: 
  ```
  Reward = Bracket Value × Multiplier
  ```
- **Bracket Value**: The value of the selected kill bracket.
- **Multiplier**:
  - Default: `0.1`
  - Tank: `0.2`
  - Healer: `0.3`

---

#### **Examples**

1. **Basic Kill Reward Distribution**
   ```
   /kills participants:@user1 @user2 @user3 bracket:10
   ```
   - **Outcome**:
     - Each participant receives `1 point` (10 kills × 0.1 multiplier).
     - Reason: `"Rewards for kill contributions in bracket 10"`

2. **With Class Modifier**
   ```
   /kills participants:@user1 @user2 bracket:50 class:healer reason:"Special kill rewards for healers"
   ```
   - **Outcome**:
     - Each participant receives `15 points` (50 kills × 0.3 multiplier).
     - Reason: `"Special kill rewards for healers"`

3. **High Kill Bracket with Tanks**
   ```
   /kills participants:@user4 @user5 @user6 bracket:100+ class:tank
   ```
   - **Outcome**:
     - Each participant receives `20 points` (100 kills × 0.2 multiplier).
     - Reason: `"Rewards for kill contributions in bracket 100+"`

4. **Custom Reason Without Class Modifier**
   ```
   /kills participants:@user1 @user2 bracket:20 reason:"Contribution to guild defense event"
   ```
   - **Outcome**:
     - Each participant receives `2 points` (20 kills × 0.1 multiplier).
     - Reason: `"Contribution to guild defense event"`
