### ISSUE TITLE
Pass Points Incentives for Large Groups

### ISSUE THREAD

**Issue by Miller-Whighte** [Aardenfell/TheHolyAutomation#9]
**Is your feature request related to a problem? Please describe.**
A way to further incentivize passing on items, especially in large groups.

**Describe the solution you'd like**
The easiest solution might be an expected minimum earned for Passing on NGPs. I'd suggest thresholds of:

.5 for Purple Raid NGPs
1 for Purple World Boss NGPs
2 for sellable NGPs
4 for Archboss NGPs 

**Describe alternatives you've considered**
Scaling the pool of points available to consider amount of participants or how highly desired the item is. This would not scale 1-1 with participants or amount of needs, but could allow for more points to be earned when there are many members. 

**Additional context**

**Comment by Miller-Whighte** [comment]
pog thanks homie! sorry i couldnt seem to add tags to any of the "issues" i posted haha

**Comment by Aardenfell** [comment]
> pog thanks homie! sorry i couldnt seem to add tags to any of the "issues" i posted haha

yeah mb. i meant to add the labels/tags in the issue template
